title: "Magitronix"
author: "Andrew Huster"
description: "This is a blog, about things."
more: "read more »"
url: "https://ahuster.github.io/"
baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md
  - bandnames.md

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - fas fa-podcast: "https://goodstuff.fm/noidea"
  - fab fa-github: "https://github.com/ahuster/"
  - fas fa-envelope: "mailto:ahuster@fastmail.com"
  - fab fa-twitter: "https://twitter.com/ahuster"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
