### GENERAL SETTINGS ###

# Site settings
title: IPPN
description: "International Posit Podcast Network"

analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ahuster.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://twitter.com/IPPN
  - title: globe
    url: http://buddybox.me/
  - title: medium
    url: http://medium.com/IPPN

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: hello@ippn.audio

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Aaron L.M. Goodwin
    position: CEO
    text: Aaron is the visionary who founded IPPN.
    img: agoodwin.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/AaronLMGoodwin
  - name: Andrew Huster
    position: Vice President for Special Business
    text: Andrew leads special projects and new verticals for IPPN.
    img: ahuster.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/ahuster
  - name: Adam Anderson
    position: Chief Content Officer
    text: Adam is in charge of editing because he finds that enjoyable.
    img: aanderson.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/ThatAdamKid
  - name: Andrew Savage
    position: Marketing
    text: We put Andrew in charge of marketing for some reason.
    img: asavage.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/A_Sav

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "IPPN, the International Posit Podcast Network, is the premiere network for transcendant digital-native mutimedia experiences and zany internet verticals."
